### ISSUE TITLE
运行导出脚本出现错误

### ISSUE THREAD

**Issue by XoYaPeng** [lhish/Vocabulary-Export#1]
大佬好，我在运行导出脚本的时候，出现下列错误，不知道#79行是什么问题，你有时间帮忙看看。
`for (const sentence of item.sentenceList) {`
![image](https://github.com/user-attachments/assets/ff4ccb12-15d9-45b6-aaf8-d5aff970a25f)

**Comment by lhish** [comment]
在电脑上选择edge或chrome或有任何有插件的浏览器，安装油猴，并通过油猴安装脚本脚本链接在主页右边给出了

**Comment by XoYaPeng** [comment]
> 在电脑上选择edge或chrome或有任何有插件的浏览器，安装油猴，并通过油猴安装脚本脚本链接在主页右边给出了

明白了嘿嘿，我刚才试了下，，不背单词页面没有导出按钮，是哪里出了问题？搭不搭梯子都没有导出按钮😂，也加载了好久

![image](https://github.com/user-attachments/assets/d126976c-566c-4031-b2b8-c826713d4f88)

**Comment by lhish** [comment]
你没有真正的启用脚本，启用的话右上角油猴处会有显示
![image](https://github.com/user-attachments/assets/55e022f2-9a85-451e-a451-11290d8bd55e)
并且该网页的界面也会变化成
![image](https://github.com/user-attachments/assets/b75ae21e-9ed4-4563-8be6-e3264be3fdff)

**Comment by XoYaPeng** [comment]
@lhish 它真的是不理我😄😄

https://github.com/user-attachments/assets/ce18e14c-7d4f-4920-a12f-254a2f5ebce5

**Comment by lhish** [comment]
请问
![image](https://github.com/user-attachments/assets/9aabc7c3-29ac-4ef6-bb2e-f5a8c05ba95b)
这个脚本工作正常吗？
另外，你的其他脚本工作正常吗？
并且你可以尝试进行重新安装

**Comment by XoYaPeng** [comment]
不背单词生词本导出这个脚本也不运行，其他脚本是正常运行的，比如下图这个。重装脚本也试了，不行
![image](https://github.com/user-attachments/assets/a28cf9b0-d4ac-45cf-9d3f-961b26d9c18e)

**Comment by lhish** [comment]
那我就不太清楚了，我也只是在它的脚本的基础上改的，如果他的能运行，那么我的也能运行，你可以去问问原作者，另外，你可以看看你的设置是否有什么问题

**Comment by XoYaPeng** [comment]
@lhish 抱歉，老哥。之前咩有注意到，需要打卡脚本页面的那个网址才可以运行脚本，刚才整好了！感谢你
